{{- $globals := ternary .Values.global.stage (ternary .Values.global.prod .Values.global.dev (eq .Values.global.env_name "prod")) (eq .Values.global.env_name "stage") -}}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-backend
type: Opaque
data:
  appKey: {{ $globals.app.key | b64enc }}
  pgsqlPassword: {{ $globals.pgsql.password | b64enc }}
  redisPassword: {{ $globals.redis.password | b64enc }}
  mailPassword: {{ $globals.mail.password | b64enc }}
  s3AccessKey: {{ $globals.aws.access_key | b64enc }}
  s3SecretKey: {{ $globals.aws.secret_key | b64enc }}
  jwtPrivateKey: {{ $globals.jwt.key.private | b64enc }}
  jwtPublicKey: {{ $globals.jwt.key.public | b64enc }}
  centrifugalApiKey: {{ $globals.centrifugal.api_key | b64enc }}
  centrifugalSecretKey: {{ $globals.centrifugal.secret_key | b64enc }}
  greenfieldApiKey: {{ $globals.greenfield.api_key | b64enc }}
  greenfieldStoreId: {{ $globals.greenfield.store_id | b64enc }}
  paymentApiKey: {{ $globals.payment.api_key | b64enc }}
  paymentCallbackKey: {{ $globals.payment.callback_key | b64enc }}
  mailchimpApiKey: {{ $globals.mailchimp.api_key | b64enc }}
  merchant01ApiKey: {{ $globals.merchant01.api_key | b64enc }}
  kafkaPassword: {{ $globals.kafka.password | b64enc }}
  googleSecret: {{ $globals.google_auth.client_secret | b64enc }}
  applePrivateKey: {{ $globals.apple_auth.private_key | b64enc }}
  appleTeamId: {{ $globals.apple_auth.team_id | b64enc }}
  appleServiceId: {{ $globals.apple_auth.service_id | b64enc }}
  appleKeyId: {{ $globals.apple_auth.key_id | b64enc }}
  telegramSecret: {{ $globals.telegram_auth.client_secret | b64enc }}
