global:
  app_name: fund-api
  prod:
    app:
      debug: "false"
    db:
      host: "postgresql-ha-pgpool.postgresql.svc.cluster.local"
      port: "5432"
      database: "backend"
      user: "backend-worker"
    redis:
      host: "redis.etf-api-service.svc.cluster.local"
      port: "26379"
      prefix: "fund"
      kafka_channel: "messages_for_kafka"
    mail:
      host: "smtp.gmail.com"
      port: "465"
      username: "support@bitcoinetf.org"
      encryption: "tls"
      address: "support@bitcoinetf.org"
      name: "BitcoinETF"
    aws:
      region: "eu-north-1"
      bucket: "etf"
      endpoint: "https://files.bitcoinetf.org"
    jwt:
      ttl:
        access: "420"
        refresh: "10080"
    centrifugal:
      host: "centrifugo.etf-api-service.svc.cluster.local:9000/api"
    greenfield:
      host: "https://btc.techetf.org"
    payment:
      host: "http://payments.etf-private-payment.svc.cluster.local:3000"
    mailchimp:
      server_prefix: "us10"
      list_id: "3a78876f55"
    merchant01:
      host: "https://api.merchant001.io"
    kafka:
      brokers: "kafka.kafka.svc.cluster.local:9092"
      consumer: "fund"
      reset: "beginning"
      username: "php-backend"
    google_auth:
      client_id: "981820521247-mee663n9a5i3qhg1eftd0un5ku1r9en7.apps.googleusercontent.com"
      redirect_uri: "https://bitcoinetf.org/auth/google"
    apple_auth:
      redirect_uri: "https://bitcoinetf.org/auth/apple"
      secret_key_file_path: "app/apple/auth/"
      secret_key_file_name: "private.pem"
    telegram_auth:
      bot_name: "BitcoinETF_loginbot"
      redirect_uri: "https://bitcoinetf.org/auth/telegram"

  stage:
    app:
      debug: "true"
    db:
      host: "postgresql-ha-pgpool.postgresql.svc.cluster.local"
      port: "5432"
      database: "php-backend"
      user: "team-worker"
    redis:
      host: "redis.etf-api-service-development.svc.cluster.local"
      port: "26379"
      prefix: "fund"
      kafka_channel: "messages_for_kafka"
    mail:
      host: "smtp.gmail.com"
      port: "465"
      username: "support@bitcoinetf.org"
      encryption: "tls"
      address: "support@bitcoinetf.org"
      name: "BitcoinETF"
    aws:
      region: "eu-north-1"
      bucket: "etf-stage"
      endpoint: "https://files.bitcoinetf.org"
    jwt:
      ttl:
        access: "420"
        refresh: "10080"
    centrifugal:
      host: "centrifugo.etf-api-service-development.svc.cluster.local:9000/api"
    greenfield:
      host: "https://btc.stage.techetf.org"
    payment:
      host: "payments.stage-etf-private-payment.svc.cluster.local:3000"
    mailchimp:
      server_prefix: "us10"
      list_id: "3a78876f55"
    merchant01:
      host: "https://api.merchant001.io"
    kafka:
      brokers: "kafka.etf-api-service-development.svc.cluster.local:9092"
      consumer: "fund"
      reset: "beginning"
      username: "php-backend"
    google_auth:
      client_id: "745955834530-cp4m04pm6sv2emqkll922blijde5o1u2.apps.googleusercontent.com"
      redirect_uri: "https://front.stage.techetf.org/auth/google"
    apple_auth:
      redirect_uri: "https://front.stage.techetf.org/auth/apple"
      secret_key_file_path: "app/apple/auth/"
      secret_key_file_name: "private.pem"
    telegram_auth:
      bot_name: "BitcoinETFlogin_bot"
      redirect_uri: "https://front.stage.techetf.org/auth/telegram"
    apollo_payment:
      host_name: "https://app.apollopayment.io"
      public_key: "XomXtTdVL6I9JNAnAgl06KTISNfR1DhLSnXnLN+PtrTfkpRPdlRtiQR+b/zcw8tGV+Vo62fjpAxh6c5oPH8ALA=="
      private_key: "TjF+TTg6J9TExAmRvg1l55sPqY+BCh8Lw9RUqgojHH90XeDLP8thH1rcxZAAq4w4DQS/jABHzFjoaOu0mZ0crQ=="
    facebook_auth:
      redirect_uri: "https://front.stage.techetf.org/auth/facebook"
      client_id: "934423128173330"
      client_secret: "b0a0d7c81f7edf8e2fab996558960b16"

otherServices:
  - name: queue
    cmd: sh
    args:
      - -c
      - php artisan queue:work
  - name: schedule
    cmd: sh
    args:
      - -c
      - php artisan schedule:work
  - name: statistic-report-monthly-account-report
    cmd: sh
    args:
      - -c
      - php artisan queue:work --tries=12 --queue=statistic.report.monthly_account_report
